# Generated by Django 5.2.6 on 2025-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('temperature_c', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall_mm', models.FloatField()),
            ],
        ),
    ]
